# Generated by Django 5.1.6 on 2025-03-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografias_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
