# Generated by Django 5.1.6 on 2025-03-25 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografias_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
