# Generated by Django 5.1.6 on 2025-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografias_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('NEBULOSA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
