# Generated by Django 5.1.6 on 2025-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografias_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
